### ISSUE TITLE
support bower

### ISSUE THREAD

**Issue by wolxXx** [boguz/Spinners#8]
it would be awesome and easy to use, if the spinners are available as a bower package. 
it is super easy to add a package: https://bower.io/docs/creating-packages/

thanks in advance!

**Comment by boguz** [comment]
that sounds like a good idea. i have never used bower, and i'm not actually sure what it is, how it works, or why people use it. i'll need to do some research...   ;)

But i would be happy if someone want to help out with that!   ;)

**Comment by wolxXx** [comment]
check the url: https://bower.io/docs/creating-packages/#register

i can do it later after work if you want.

**Comment by boguz** [comment]
sure, that would be great!   =)

I'll also read about it. i have heard many times about bower, but somehow i never came around to using it.

Thanks!

**Comment by wolxXx** [comment]
i created a bower.json pull request. 
you may want to change the data in there ;)

now everybody can use your spinners using bower install cssspinners 
easy :)

**Comment by boguz** [comment]
that is really great. nice job. THANKS!   =)

I'll now put also on the "website" and on the README some information on how to use it via bower...
;)

**Comment by wolxXx** [comment]
yeah. thank you for your work! i really like the spinners.

**Comment by boguz** [comment]
Hi. i have just updated the files (added some new animations).

How can one update de bower package? does it update alone according to what is where on github?

On the bower.json file there is a "ignore" part.
I have been reading about but still am not sure how it works. I would like that the people install only the "content" folder. That is what they need, so everything else is not needed.
Could you please point me to a place where i could learn about this?

Thank you!!!   =)

**Comment by wolxXx** [comment]
updates will be received by those who run the bower update command.
every time you push a new commit commit to the master branch, it will be available. give the bower repository at least five minutes. they do not check the repositories every second ;)

to achieve that only dedicated files / directories will be sent to the bower user, you will need to create a package and create tags for them. this is kind of complex ;)
it is not possible via bower to say which directories will be deployed. (but this information it got may be errorous. hopefully this feature is available now)

**Comment by wolxXx** [comment]
have a look at https://github.com/jquery/jquery respective https://github.com/jquery/jquery/tags

they build a version and create a tag. 
and if you use bower to receive jquery, you will get the "dist" and the "src".

**Comment by boguz** [comment]
thanks!
